
title = "blog"
explain = "wetor个人blog"
mode = "dev"
addr = ":88"
srv = "http://localhost:8085"

jwtkey = "12345876"
jwtexp = 8

[author]
name = "wetorx"
website = "https://github.com/wetorx"

[wechat]
appid = "appid"
secret = "secret"

[database]
host = "localhost"
port = 3306
user = "root"
passwd = "123456"
dbname = "blog"
params = "charset=utf8&parseTime=true"

[xorm]
idle = 4
open = 8
show = true
sync = false
cache_enable = false
cache_count = 1000

